name: "TestCronEvery5Min"

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  showTime:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event.head_commit != null && !contains(github.event.head_commit.message, '[LoLi-Bot]')) }}

    runs-on: ubuntu-latest
    steps:
      - run: | 
        echo "UTC now: $(date -u)"
